version: '3.5'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_DATABASE}
      NODE_ENV: development
      PORT: ${LOCAL_APP_PORT}
    ports:
      - 8080:${LOCAL_APP_PORT}
    volumes:
      - app-data:/app/data
    container_name: bazaskill-backend

  postgres:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:${LOCAL_DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: bazaskill-postgres

volumes:
  app-data:
  db-data:
